# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-Git3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-Git3
pod "PGFramework"
  target 'Test-Git3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-Git3UITests' do
    # Pods for testing
  end

end
